import { useUI } from './store'

const en = {
  home: 'Home', intelligence: 'Intelligence center', report: 'Report problem', crops: 'My crops', alerts: 'Nearby alerts', reports: 'My reports', weather: 'Weather', market: 'Market intelligence', recommendations: 'Seed & fertilizer', admin: 'Admin dashboard', farm: 'Farm profile', notifications: 'Notifications', settings: 'Settings',
  reportTitle: 'Report a crop problem', reportIntro: 'Submit an observation for weather context, crop analysis, and a conservative risk check.', cropField: 'Tell us about the crop', crop: 'Crop', field: 'Field', district: 'District', useLocation: 'Use browser location', latitude: 'Latitude', longitude: 'Longitude', showProblem: 'Show us the problem', uploadPhoto: 'Upload image', useCamera: 'Use camera', symptomsHeading: 'Describe what you notice', symptoms: 'Symptoms', notes: 'Additional notes', voice: 'Describe by voice', confirmVoice: 'Use transcription', transcript: 'Review transcription', submit: 'Submit crop report', retry: 'Retry saved analysis', analyzing: 'Analyzing report...', waitingSync: 'Waiting to Sync', syncNow: 'Sync now', offline: 'Offline', online: 'Online', language: 'Language',
  farmTitle: 'Farm & soil profile', save: 'Save profile', marketTitle: 'Market intelligence', seedTitle: 'Seed & nutrient guidance', notificationsTitle: 'Notifications', cropsTitle: 'My crops', healthTitle: 'Provider health',
} as const
export type TranslationKey = keyof typeof en
type Key = TranslationKey
const te: Partial<Record<Key, string>> = {
  home: 'హోమ్', intelligence: 'విశ్లేషణ కేంద్రం', report: 'సమస్యను నివేదించండి', crops: 'నా పంటలు', alerts: 'సమీప హెచ్చరికలు', reports: 'నా నివేదికలు', weather: 'వాతావరణం', market: 'మార్కెట్ సమాచారం', recommendations: 'విత్తనాలు & ఎరువులు', admin: 'నిర్వాహక డాష్‌బోర్డ్', farm: 'పొలం వివరాలు', notifications: 'నోటిఫికేషన్‌లు', settings: 'సెట్టింగ్‌లు',
  reportTitle: 'పంట సమస్యను నివేదించండి', reportIntro: 'పంట లక్షణాలను నమోదు చేసి విశ్లేషణ పొందండి.', cropField: 'పంట వివరాలు', crop: 'పంట', field: 'పొలం', district: 'జిల్లా', useLocation: 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి', latitude: 'అక్షాంశం', longitude: 'రేఖాంశం', showProblem: 'సమస్య ఫోటో', uploadPhoto: 'ఫోటో అప్‌లోడ్', useCamera: 'కెమెరా ఉపయోగించండి', symptomsHeading: 'గమనించిన లక్షణాలు', symptoms: 'లక్షణాలు', notes: 'అదనపు గమనికలు', voice: 'మాట్లాడి వివరించండి', confirmVoice: 'వచనాన్ని ఉపయోగించండి', transcript: 'వచనాన్ని పరిశీలించండి', submit: 'నివేదికను పంపండి', retry: 'మళ్లీ ప్రయత్నించండి', analyzing: 'విశ్లేషిస్తోంది...', waitingSync: 'సమకాలీకరణ కోసం వేచి ఉంది', syncNow: 'ఇప్పుడు సమకాలీకరించు', offline: 'ఆఫ్‌లైన్', online: 'ఆన్‌లైన్', language: 'భాష', farmTitle: 'పొలం & నేల వివరాలు', save: 'సేవ్ చేయండి', marketTitle: 'మార్కెట్ సమాచారం', seedTitle: 'విత్తన & పోషక మార్గదర్శకం', notificationsTitle: 'నోటిఫికేషన్‌లు', cropsTitle: 'నా పంటలు', healthTitle: 'సేవల స్థితి',
}
const hi: Partial<Record<Key, string>> = {
  home: 'होम', intelligence: 'विश्लेषण केंद्र', report: 'समस्या दर्ज करें', crops: 'मेरी फसलें', alerts: 'आसपास की चेतावनी', reports: 'मेरी रिपोर्ट', weather: 'मौसम', market: 'बाज़ार जानकारी', recommendations: 'बीज और उर्वरक', admin: 'प्रशासन डैशबोर्ड', farm: 'खेत की जानकारी', notifications: 'सूचनाएँ', settings: 'सेटिंग्स',
  reportTitle: 'फसल की समस्या दर्ज करें', reportIntro: 'फसल के लक्षण दर्ज करके विश्लेषण प्राप्त करें।', cropField: 'फसल की जानकारी', crop: 'फसल', field: 'खेत', district: 'ज़िला', useLocation: 'ब्राउज़र स्थान लें', latitude: 'अक्षांश', longitude: 'देशांतर', showProblem: 'समस्या की तस्वीर', uploadPhoto: 'तस्वीर अपलोड करें', useCamera: 'कैमरा उपयोग करें', symptomsHeading: 'आपने क्या देखा', symptoms: 'लक्षण', notes: 'अतिरिक्त जानकारी', voice: 'बोलकर बताएँ', confirmVoice: 'लिखा हुआ उपयोग करें', transcript: 'लिखा हुआ जाँचें', submit: 'फसल रिपोर्ट भेजें', retry: 'फिर विश्लेषण करें', analyzing: 'विश्लेषण जारी है...', waitingSync: 'सिंक की प्रतीक्षा', syncNow: 'अब सिंक करें', offline: 'ऑफ़लाइन', online: 'ऑनलाइन', language: 'भाषा', farmTitle: 'खेत और मिट्टी की जानकारी', save: 'सहेजें', marketTitle: 'बाज़ार जानकारी', seedTitle: 'बीज और पोषक मार्गदर्शन', notificationsTitle: 'सूचनाएँ', cropsTitle: 'मेरी फसलें', healthTitle: 'सेवा की स्थिति',
}
const dictionaries = { en, te, hi }
export function translate(language: 'en' | 'te' | 'hi', key: Key): string { return dictionaries[language][key] ?? en[key] }
export function useTranslation() { const language = useUI(state => state.language); return { language, t: (key: Key) => translate(language, key) } }
