export type SourceStatus = 'DEMO' | 'LIVE' | 'CACHED' | 'FALLBACK'
export type Severity = 'Low' | 'Moderate' | 'High'
export interface Crop { id: string; name: string; variety: string; area: number; stage: string; health: number; planted: string; accent: string }
export interface Alert { id: string; crop: string; title: string; district: string; distance: number; severity: Severity; time: string; lat: number; lng: number; radius: number; description: string }
export interface Report { id: string; crop: string; title: string; date: string; status: 'Demo result' | 'Draft' | 'Waiting to sync'; severity: Severity; field: string }
export interface Mandi { name: string; district: string; distance: number; price: number; min: number; max: number; change: number }
export interface HealthResponse { status: 'ok'; environment: string; database: 'local_demo' | 'configured' | 'not_configured'; timestamp: string; demo_mode: boolean }
export interface ApiError { code: string; message: string; request_id?: string }

export type AIStatus = 'AI LIVE' | 'AI CACHED' | 'LOCAL KNOWLEDGE' | 'LIMITED MODE'
export interface CropFinding { possible_problem: string; confidence: number; severity: 'low' | 'moderate' | 'high'; symptoms: string[]; possible_causes: string[]; immediate_actions: string[]; precautions: string[]; monitoring: string[]; expert_verification: string; spread_potential: 'low' | 'moderate' | 'high' | 'unknown' }
export interface CropHealthResult { finding: CropFinding; source: AIStatus; model: string | null; image_assessed: boolean; knowledge_ref: string | null; analyzed_at: string; limitation: string | null }
export interface WeatherResult { latitude: number; longitude: number; source: string; provider: string | null; current: { temperature_c: number; relative_humidity_pct: number; precipitation_mm: number; wind_speed_kmh: number; weather_code: number; observed_at: string } | null; daily: { date: string; max_temperature_c: number; min_temperature_c: number; precipitation_mm: number; precipitation_probability_pct: number; weather_code: number }[]; hourly: { time: string; temperature_c: number; relative_humidity_pct: number; precipitation_probability_pct: number }[]; agricultural_indicators: string[]; fetched_at: string | null; last_updated: string | null; stale: boolean; is_synthetic: boolean }
export interface RiskResult { individual_risk: number; community_risk: number; risk_factors: string[]; recommended_monitoring: string[] }
export interface OutbreakResult { nearby_alert: boolean; alert_reason: string; cluster_size: number; risk_radius_km: number; confidence: number; evidence_is_synthetic: boolean }
export interface LiveReport { id: string; crop: string; field: string; district: string; symptom_description: string; notes: string | null; latitude: number; longitude: number; status: string; stage: string; created_at: string; is_synthetic: boolean; image_url: string | null; crop_health: CropHealthResult | null; weather: WeatherResult | null; risk: RiskResult | null; outbreak: OutbreakResult | null; nearby_count: number; nearby_synthetic_count: number }
export interface NearbyCluster { id: string; crop: string; possible_problem: string; district: string; severity: 'low' | 'moderate' | 'high'; cluster_size: number; distance_km: number; risk_radius_km: number; latitude: number; longitude: number; observed_at: string; is_synthetic: boolean }
export interface AnalysisEvent { stage: string; status: string; report?: LiveReport; message?: string }

export interface FarmProfileInput { farm_name?: string | null; village?: string | null; district?: string | null; latitude?: number | null; longitude?: number | null; area_acres?: number | null; crop?: string | null; season?: string | null; soil_type?: string | null; soil_ph?: number | null; nitrogen_kg_ha?: number | null; phosphorus_kg_ha?: number | null; potassium_kg_ha?: number | null; micronutrients?: Record<string, number>; lab_status?: Record<string, 'low' | 'adequate' | 'high'>; previous_crop?: string | null; irrigation?: string | null; budget_inr?: number | null; planting_date?: string | null }
export interface FarmProfile extends FarmProfileInput { updated_at: string; is_synthetic: boolean }
export interface PortfolioInput { crop: string; field: string; planting_date?: string | null; area_acres?: number | null; season?: string | null; health_status: 'unknown' | 'healthy' | 'watch' | 'needs_attention'; next_action?: string | null }
export interface PortfolioCrop extends PortfolioInput { id: string; created_at: string; updated_at: string; latest_report_id?: string | null; latest_report_at?: string | null; latest_risk?: number | null; is_synthetic: boolean }
export interface NotificationItem { id: string; kind: string; title: string; body: string; target_url: string | null; created_at: string; read_at: string | null; is_synthetic: boolean }
export interface AdminOverview { source: string; counts: { farmers: number; farms: number; reports: number; clusters: number; notifications: number }; crops: { crop: string; count: number }[]; clusters: { id: string; crop: string; possible_problem: string; district: string; latitude: number; longitude: number; report_count: number; is_synthetic: boolean }[] }
export interface MarketQuote { commodity: string; variety: string; state: string; district: string; mandi: string; min_price: number; max_price: number; modal_price: number; date: string; latitude: number | null; longitude: number | null; distance_km: number | null; source: 'LIVE' | 'CACHED' | 'FALLBACK'; is_synthetic: boolean; provenance: string }
export interface MarketHistoryPoint { date: string; modal_price: number; sample_count: number }
export interface MarketResponse { commodity: string; district: string | null; source: 'LIVE' | 'CACHED' | 'FALLBACK'; is_synthetic: boolean; stale: boolean; fetched_at: string | null; last_updated: string | null; provenance: string; quotes: MarketQuote[]; history_7d: MarketHistoryPoint[]; history_30d: MarketHistoryPoint[] }
export interface MarketTrend { trend: 'RISING' | 'STABLE' | 'FALLING' | 'UNAVAILABLE'; confidence: number; reasoning_summary: string; forecast_horizon: string; source: 'AI LIVE' | 'AI CACHED' | 'DETERMINISTIC' | 'UNAVAILABLE'; is_synthetic: boolean; limitation: string }
export interface MarketEstimateInput { quantity_quintals: number; modal_price_per_quintal: number; distance_km: number; transport_cost_per_km: number; handling_cost_per_quintal: number; storage_cost: number; spoilage_percent: number }
export interface MarketEstimate { quantity_quintals: string; gross_revenue: string; transport_cost: string; handling_cost: string; storage_cost: string; estimated_spoilage: string; total_cost: string; estimated_net_return: string; note: string }
export interface SeedRecommendation { crop: string | null; suitability: 'potentially_suitable' | 'needs_review' | 'insufficient_data'; characteristics: string[]; considerations: string[]; missing_inputs: string[]; provenance: string; is_product_recommendation: false }
export interface FertilizerRecommendation { nutrient_status: Record<string, string>; possible_deficiencies: string[]; priorities: string[]; soil_considerations: string[]; general_direction: string[]; monitoring: string[]; missing_inputs: string[]; provenance: string; exact_dose_provided: false }
export interface ProviderHealth { providers: { name: string; state: 'Healthy' | 'Degraded' | 'Cached' | 'Fallback' | 'Unavailable'; observed_at: string | null; detail: string }[] }
