"""Application-owned repository interfaces; route and agent code use these."""

from typing import Any, Protocol
from uuid import UUID

from app.schemas.entities import CropCreate, CropRecord, FarmCreate, FarmRecord, SoilTestCreate, SoilTestRecord


class HealthRepository(Protocol):
    async def check_database(self) -> bool: ...


class FarmerRepository(Protocol):
    async def get_profile(self, farmer_id: UUID) -> dict[str, Any] | None: ...


class FarmRepository(Protocol):
    async def get_owned(self, farm_id: UUID, farmer_id: UUID) -> FarmRecord | None: ...
    async def list_for_farmer(self, farmer_id: UUID) -> list[FarmRecord]: ...
    async def create(self, farm: FarmCreate, farmer_id: UUID) -> FarmRecord: ...


class CropRepository(Protocol):
    async def list_for_farm(self, farm_id: UUID) -> list[CropRecord]: ...
    async def create(self, crop: CropCreate) -> CropRecord: ...


class SoilTestRepository(Protocol):
    async def latest_for_farm(self, farm_id: UUID) -> SoilTestRecord | None: ...
    async def create(self, farm_id: UUID, soil_test: SoilTestCreate) -> SoilTestRecord: ...


class ReportRepository(Protocol):
    async def get_owned(self, report_id: UUID, farmer_id: UUID) -> dict[str, Any] | None: ...
    async def list_for_farmer(self, farmer_id: UUID) -> list[dict[str, Any]]: ...
