import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { FlaskConical, Info, Leaf, Sprout } from 'lucide-react'
import { api } from '../../lib/api'
import { useTranslation } from '../../lib/i18n'
import type { FertilizerRecommendation, SeedRecommendation } from '../../lib/types'
import { EmptyState, PageHeader, Panel, SectionHead, Skeleton } from '../../components/UI'

export default function Recommendations() {
  const { t } = useTranslation()
  const profile = useQuery({ queryKey: ['farm-profile'], queryFn: api.farmProfile })
  const [tab, setTab] = useState<'seed' | 'nutrient'>('seed')
  const [seed, setSeed] = useState<SeedRecommendation | null>(null)
  const [nutrient, setNutrient] = useState<FertilizerRecommendation | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  async function generate() { if (!profile.data) return; setBusy(true); setError(''); try { if (tab === 'seed') setSeed(await api.seedRecommendation(profile.data)); else setNutrient(await api.fertilizerRecommendation(profile.data)) } catch (caught) { setError(caught instanceof Error ? caught.message : t('guidanceUnavailable')) } finally { setBusy(false) } }
  return <div className="page"><PageHeader eyebrow="FIELD PLANNING / INPUTS" title={t('seedTitle')} description={t('seedDescription')} action={<Link to="/farm" className="button secondary">{t('editFarmSoil')}</Link>}/>{profile.isPending ? <Skeleton className="result-loading"/> : profile.isError ? <EmptyState title={t('farmProfileUnavailable')} body={profile.error.message}/> : !profile.data ? <EmptyState title={t('addFarmContextFirst')} body={t('addFarmContextBody')} action={<Link className="button primary" to="/farm">{t('createProfile')}</Link>}/> : <><div className="tab-row"><button className={tab === 'seed' ? 'selected' : ''} onClick={() => setTab('seed')}><Sprout size={16}/> {t('seedSuitability')}</button><button className={tab === 'nutrient' ? 'selected' : ''} onClick={() => setTab('nutrient')}><FlaskConical size={16}/> {t('nutrientGuidanceTab')}</button></div><Panel className="p3-guidance-intro"><div><Leaf size={24}/><h2>{tab === 'seed' ? t('characteristicGuidance') : t('soilTestInterpretation')}</h2></div><p>{tab === 'seed' ? t('noCommercialBrands') : t('rawNutrientValues')}</p><button className="button primary" disabled={busy} onClick={generate}>{busy ? t('preparing') : t('generateGuidance')}</button></Panel>{error && <p className="form-error" role="alert">{error}</p>}{tab === 'seed' && seed && <div className="p3-guidance-grid"><Panel><SectionHead title={t('suitability')}/><strong className="p3-guidance-status">{seed.suitability.replace('_', ' ')}</strong><h3>{t('lookFor')}</h3><ul>{seed.characteristics.map(item => <li key={item}>{item}</li>)}</ul></Panel><Panel><SectionHead title={t('fieldConsiderations')}/><ul>{seed.considerations.map(item => <li key={item}>{item}</li>)}</ul>{seed.missing_inputs.length > 0 && <p>{t('missingInputs')}: {seed.missing_inputs.join(', ')}.</p>}</Panel></div>}{tab === 'nutrient' && nutrient && <div className="p3-guidance-grid"><Panel><SectionHead title={t('recordedNutrientStatus')}/>{Object.entries(nutrient.nutrient_status).map(([name, value]) => <div className="admin-line" key={name}><span>{name}</span><strong>{value}</strong></div>)}<h3>{t('possibleDeficiencies')}</h3>{nutrient.possible_deficiencies.length ? <ul>{nutrient.possible_deficiencies.map(item => <li key={item}>{item}</li>)}</ul> : <p>None inferred without a supplied low laboratory category.</p>}</Panel><Panel><SectionHead title={t('prioritiesAndMonitoring')}/><ul>{[...nutrient.priorities, ...nutrient.soil_considerations, ...nutrient.general_direction, ...nutrient.monitoring].map(item => <li key={item}>{item}</li>)}</ul>{nutrient.missing_inputs.length > 0 && <p>{t('missingInputs')}: {nutrient.missing_inputs.join(', ')}.</p>}</Panel></div>}{(seed || nutrient) && <p className="p2-attribution"><Info size={14}/> {tab === 'seed' ? seed?.provenance : nutrient?.provenance}. Expert verification is useful before changing field practice.</p>}</>}</div>
}
