import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { useReducedMotion, motion } from 'framer-motion'
import { Activity, ArrowRight, CloudSun, Leaf, MapPin, Plus, Sprout } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { api } from '../../lib/api'
import { useQueueStatus } from '../../lib/useQueueStatus'
import { EmptyState, Eyebrow, Panel, SectionHead, Skeleton, Stat } from '../../components/UI'

const money = (value: number) => `₹${Math.round(value).toLocaleString('en-IN')}`

export default function Home() {
  const reducedMotion = useReducedMotion()
  const queue = useQueueStatus()
  const health = useQuery({ queryKey: ['health'], queryFn: api.health, retry: false })
  const profile = useQuery({ queryKey: ['farm-profile'], queryFn: api.farmProfile, retry: false })
  const crops = useQuery({ queryKey: ['portfolio'], queryFn: api.portfolio, retry: false })
  const reports = useQuery({ queryKey: ['reports'], queryFn: api.reports, retry: false })
  const notifications = useQuery({ queryKey: ['notifications'], queryFn: api.notifications, retry: false })
  const coordinates = profile.data?.latitude != null && profile.data.longitude != null ? [profile.data.latitude, profile.data.longitude] as const : null
  const weather = useQuery({ queryKey: ['weather', coordinates], queryFn: () => api.weather(coordinates![0], coordinates![1]), enabled: Boolean(coordinates), retry: false })
  const market = useQuery({ queryKey: ['market-prices', 'Cotton', profile.data?.district], queryFn: () => api.marketPrices('Cotton', profile.data?.district ?? undefined), retry: false })
  const alerts = useQuery({ queryKey: ['nearby-alerts', 'Cotton', coordinates], queryFn: () => api.nearbyAlerts('Cotton', coordinates![0], coordinates![1]), enabled: Boolean(coordinates), retry: false })
  const recent = reports.data?.slice(0, 3) ?? []
  const latestPrice = market.data?.quotes[0]
  return <motion.div className="page home-page" initial={reducedMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .25 }}>
    <div className="home-heading"><div><Eyebrow>FIELD INTELLIGENCE / OVERVIEW</Eyebrow><h1>{profile.data?.farm_name ? `${profile.data.farm_name} overview` : 'Your field overview'}</h1><p>Reports, crop conditions, nearby signals, and market context in one workspace.</p></div><Link className="button primary" to="/report"><Plus size={17}/> Report a problem</Link></div>
    {health.data?.demo_mode && <div className="demo-notice"><Leaf size={16}/><span>Local demo workspace. Seeded farm, report, cluster, and notification records are synthetic and labelled throughout.</span></div>}
    {health.isError && <div className="form-error" role="alert">The API is unavailable. Reconnect to load your field data.</div>}
    <div className="metrics-grid p4-metrics"><Stat label="CROP FIELDS" value={crops.isPending ? '…' : String(crops.data?.length ?? 0).padStart(2, '0')} change={crops.isError ? 'Unavailable' : 'From your portfolio'} icon={<Sprout size={19}/>}/><Stat label="MY REPORTS" value={reports.isPending ? '…' : String(reports.data?.length ?? 0).padStart(2, '0')} change={reports.isError ? 'Unavailable' : 'Stored observations'} icon={<Activity size={19}/>}/><Stat label="COTTON CLUSTERS" value={alerts.isPending ? '…' : String(alerts.data?.length ?? 0).padStart(2, '0')} change={alerts.isError ? 'Unavailable' : alerts.data?.some(item => item.is_synthetic) ? 'Includes synthetic demo data' : 'Nearby observations'} icon={<MapPin size={19}/>}/><Stat label="WAITING TO SYNC" value={String(queue.count).padStart(2, '0')} change={queue.online ? 'Online' : 'Offline'} icon={<CloudSun size={19}/>}/></div>
    <div className="p4-home-grid"><Panel className="p4-hero"><Eyebrow>CROP HEALTH / ACTION CENTER</Eyebrow><h2>See the field clearly.<br/><em>Act with context.</em></h2><p>Submit a crop image and symptoms. The analysis links possible issues with weather, nearby activity, and conservative risk guidance.</p><div className="p4-hero-actions"><Link className="button primary" to="/report">Start crop analysis <ArrowRight size={16}/></Link><Link className="button secondary" to="/intelligence">Explore intelligence</Link></div><div className="p4-hero-orbit" aria-hidden="true"><Leaf size={88}/></div></Panel><Panel className="p4-signal"><SectionHead title="Weather context" to="/weather"/><span className={`source-badge source-${weather.data?.source === 'LIVE' ? 'live' : weather.data?.source === 'CACHED' ? 'cached' : 'fallback'}`}>{weather.data?.source ?? (weather.isError ? 'UNAVAILABLE' : 'AWAITING DATA')}</span>{weather.isPending && coordinates ? <Skeleton className="p4-signal-skeleton"/> : weather.data?.current ? <><strong className="p4-signal-number">{Math.round(weather.data.current.temperature_c)}°C</strong><p>{weather.data.current.relative_humidity_pct}% humidity · {weather.data.current.precipitation_mm} mm precipitation</p><small>Observed {new Date(weather.data.current.observed_at).toLocaleString('en-IN')}</small></> : <p>{coordinates ? 'Weather is unavailable. Recommendations do not assume current conditions.' : 'Add farm coordinates to see local weather.'}</p>}</Panel></div>
    <div className="p4-home-grid"><Panel><SectionHead title="Recent field reports" to="/reports"/>{reports.isPending ? <Skeleton className="p4-signal-skeleton"/> : reports.isError ? <EmptyState title="Reports unavailable" body={reports.error.message}/> : recent.length ? <div className="p4-list">{recent.map(item => <Link key={item.id} to={`/result/${item.id}`} className="p4-list-row"><span className="p4-list-icon"><Activity size={17}/></span><span><strong>{item.crop} · {item.field}</strong><small>{item.crop_health?.finding.possible_problem ?? `Analysis ${item.status}`} · {new Date(item.created_at).toLocaleDateString('en-IN')}</small></span><span className={`source-badge source-${item.is_synthetic ? 'demo' : item.crop_health?.source === 'AI LIVE' ? 'live' : 'fallback'}`}>{item.is_synthetic ? 'SYNTHETIC' : item.crop_health?.source ?? item.status}</span></Link>)}</div> : <EmptyState title="No reports yet" body="Your submitted crop observations will appear here." action={<Link className="button secondary" to="/report">Create report</Link>}/>}</Panel><Panel><SectionHead title="Cotton market pulse" to="/market"/>{market.isPending ? <Skeleton className="p4-signal-skeleton"/> : market.isError ? <EmptyState title="Market unavailable" body={market.error.message}/> : <><div className="p4-market-top"><strong>{latestPrice ? money(latestPrice.modal_price) : 'No quote'}</strong><span className={`source-badge source-${market.data?.source.toLowerCase()}`}>{market.data?.is_synthetic ? 'SYNTHETIC ' : ''}{market.data?.source}</span></div><small>Modal price per quintal · {latestPrice?.mandi ?? 'No mandi'} · observed {market.data?.last_updated ?? 'unknown'}</small><div className="p4-mini-chart" role="img" aria-label="Cotton modal price history"><ResponsiveContainer width="100%" height="100%"><AreaChart data={market.data?.history_30d ?? []}><XAxis dataKey="date" hide/><Tooltip formatter={(value) => money(Number(value))}/><Area dataKey="modal_price" type="monotone" stroke="#81dba6" fill="#81dba62b" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></>}</Panel></div>
    <div className="p4-home-grid"><Panel><SectionHead title="Nearby cotton activity" to="/alerts"/>{alerts.isPending && coordinates ? <Skeleton className="p4-signal-skeleton"/> : alerts.data?.length ? <div className="p4-list">{alerts.data.slice(0, 3).map(item => <Link className="p4-list-row" to="/alerts" key={item.id}><span className="p4-list-icon"><MapPin size={17}/></span><span><strong>{item.possible_problem}</strong><small>{item.cluster_size} reports · {item.distance_km.toFixed(1)} km · {item.district}</small></span><span className={`source-badge source-${item.is_synthetic ? 'demo' : 'live'}`}>{item.is_synthetic ? 'SYNTHETIC' : 'REPORTED'}</span></Link>)}</div> : <p className="p4-muted">{alerts.isError ? 'Nearby activity is unavailable.' : 'No matching cotton clusters in this area.'}</p>}</Panel><Panel><SectionHead title="Inbox" to="/notifications"/>{notifications.isPending ? <Skeleton className="p4-signal-skeleton"/> : notifications.data?.length ? <div className="p4-list">{notifications.data.slice(0, 3).map(item => <Link className="p4-list-row" to={item.target_url ?? '/notifications'} key={item.id}><span className="p4-list-icon"><Activity size={17}/></span><span><strong>{item.title}</strong><small>{item.body}</small></span>{item.is_synthetic && <span className="source-badge source-demo">SYNTHETIC</span>}</Link>)}</div> : <p className="p4-muted">{notifications.isError ? 'Notifications unavailable.' : 'No notifications yet.'}</p>}</Panel></div>
  </motion.div>
}
