import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, Calculator, MapPin, TrendingUp } from 'lucide-react'
import { api } from '../../lib/api'
import { demoFarm } from '../../lib/demo'
import { useTranslation } from '../../lib/i18n'
import type { MarketEstimate, MarketEstimateInput } from '../../lib/types'
import { EmptyState, PageHeader, Panel, SectionHead, Skeleton } from '../../components/UI'

const commodities = ['Cotton', 'Paddy', 'Maize', 'Chilli', 'Tomato', 'Groundnut', 'Red gram', 'Green gram', 'Black gram', 'Soybean', 'Turmeric', 'Onion', 'Potato', 'Wheat', 'Sorghum', 'Pearl millet']
const districts = ['All', 'Hyderabad', 'Rangareddy', 'Medchal', 'Warangal', 'Karimnagar', 'Nizamabad', 'Khammam', 'Mahbubnagar', 'Adilabad']
const money = (value: number | string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(Number(value))

export default function Market() {
  const { t } = useTranslation()
  const [commodity, setCommodity] = useState('Cotton')
  const [district, setDistrict] = useState('All')
  const [period, setPeriod] = useState<7 | 30>(7)
  const [selected, setSelected] = useState('')
  const [comparison, setComparison] = useState('')
  const [estimateInputs, setEstimateInputs] = useState<MarketEstimateInput>({ quantity_quintals: 0, modal_price_per_quintal: 0, distance_km: 0, transport_cost_per_km: 0, handling_cost_per_quintal: 0, storage_cost: 0, spoilage_percent: 0 })
  const [estimate, setEstimate] = useState<MarketEstimate | null>(null)
  const [estimateError, setEstimateError] = useState('')
  const profile = useQuery({ queryKey: ['farm-profile'], queryFn: api.farmProfile })
  const lat = profile.data?.latitude ?? demoFarm.coordinates[0], lon = profile.data?.longitude ?? demoFarm.coordinates[1]
  const market = useQuery({ queryKey: ['market', commodity, district, lat, lon], queryFn: () => api.marketPrices(commodity, district, lat, lon), staleTime: 10 * 60_000 })
  const trend = useQuery({ queryKey: ['market-trend', commodity, district], queryFn: () => api.marketTrend(commodity, district), enabled: false })
  const data = market.data
  const quotes = data?.quotes ?? []
  const first = quotes.find(item => item.mandi === selected) ?? quotes[0]
  const second = quotes.find(item => item.mandi === comparison && item.mandi !== first?.mandi)
  const history = period === 7 ? data?.history_7d ?? [] : data?.history_30d ?? []
  async function calculate() { try { setEstimate(await api.marketEstimate(estimateInputs)); setEstimateError('') } catch (error) { setEstimateError(error instanceof Error ? error.message : 'Estimate unavailable.') } }
  function updateNumber(key: keyof MarketEstimateInput, value: string) { setEstimateInputs(current => ({ ...current, [key]: Number(value) })); setEstimate(null) }
  return <div className="page"><PageHeader eyebrow="MARKET / PRICE INTELLIGENCE" title={t('marketTitle')} description="Compare dated mandi observations and estimate returns from your own costs." action={data && <span className={`source-badge source-${data.source.toLowerCase()}`}>{data.source}{data.is_synthetic ? ' · SYNTHETIC' : ''}</span>}/>
    <div className="market-controls"><label>COMMODITY<select value={commodity} onChange={event => { setCommodity(event.target.value); setSelected(''); setComparison('') }}>{commodities.map(item => <option key={item}>{item}</option>)}</select></label><label>DISTRICT<select value={district} onChange={event => { setDistrict(event.target.value); setSelected(''); setComparison('') }}>{districts.map(item => <option key={item}>{item}</option>)}</select></label><div className="market-control-location"><MapPin size={17}/>{profile.data?.latitude != null ? 'Your saved farm location' : 'Demo search center'}</div></div>
    {market.isPending ? <Skeleton className="result-loading"/> : market.isError ? <EmptyState title="Market data unavailable" body={market.error.message} action={<button className="button secondary" onClick={() => market.refetch()}>Retry</button>}/> : <>{data?.is_synthetic && <div className="demo-notice"><span>These are fixed-seed synthetic prices dated through {data.last_updated}. They are not current official mandi quotes and must not guide a sale.</span></div>}{data?.stale && !data.is_synthetic && <div className="demo-notice"><span>Cached market observations may be outdated. Check the quoted date before any sale.</span></div>}
      <div className="market-layout"><div className="market-main"><Panel className="price-hero"><div className="price-hero-top"><span>MODAL PRICE / {commodity.toUpperCase()} / {first?.mandi.toUpperCase() ?? 'NO MANDI'}</span>{first && <TrendingUp size={20}/>}</div><div className="price-big">{first ? money(first.modal_price) : 'Unavailable'}<span> / quintal</span></div><div className="price-sub">{first ? `Observed ${first.date} · ${first.variety}` : 'No matching observation'} · {data?.source}</div>{first && <div className="price-ranges"><div><small>MIN PRICE</small><strong>{money(first.min_price)}</strong></div><div><small>MAX PRICE</small><strong>{money(first.max_price)}</strong></div><div><small>DISTANCE</small><strong>{first.distance_km != null ? `${first.distance_km} km` : 'Unknown'}</strong></div></div>}</Panel>
        <Panel className="chart-panel"><div className="chart-head"><div><h2>Price history</h2><p>Average observed modal price per quintal · {data?.is_synthetic ? 'synthetic demo' : data?.source.toLowerCase()}</p></div><div className="segmented"><button className={period === 7 ? 'active' : ''} onClick={() => setPeriod(7)}>7 days</button><button className={period === 30 ? 'active' : ''} onClick={() => setPeriod(30)}>30 days</button></div></div>{history.length ? <div className="large-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid stroke="#263a34" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="date" tick={{ fill: '#819b90', fontSize: 10 }} tickFormatter={value => value.slice(5)} axisLine={false} tickLine={false}/><YAxis tick={{ fill: '#819b90', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={value => `₹${Number(value).toFixed(0)}`}/><Tooltip contentStyle={{ background: '#17251f', border: '1px solid #385048', color: '#e8f2e9', borderRadius: 10 }} formatter={value => [money(Number(value)), 'Average modal']}/><Line type="monotone" dataKey="modal_price" stroke="#77d8a5" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div> : <EmptyState title="History unavailable" body="The provider did not return enough dated observations for this filter."/>}</Panel>
        <Panel className="p3-market-trend"><SectionHead title="Recent direction" aside={<button className="button secondary" onClick={() => trend.refetch()} disabled={trend.isFetching || !history.length}>Analyze trend</button>}/>{trend.isFetching ? <Skeleton/> : trend.data ? <><strong>{trend.data.trend}</strong><span className="source-badge source-cached">{trend.data.source}</span><p>{trend.data.reasoning_summary}</p><small>Confidence {Math.round(trend.data.confidence * 100)}% · {trend.data.forecast_horizon}</small><p className="p2-attribution">{trend.data.limitation}{trend.data.is_synthetic ? ' Based on synthetic examples.' : ''}</p></> : <p>Request an optional historical direction summary. It does not predict or guarantee future prices.</p>}{trend.isError && <p className="form-error">{trend.error.message}</p>}</Panel></div>
        <Panel className="mandi-panel"><SectionHead title="Nearby mandis"/><p>Select two observations to compare. Distances use available approximate market coordinates.</p>{quotes.map(item => <button key={`${item.mandi}-${item.variety}`} className={`mandi-row ${first?.mandi === item.mandi ? 'selected' : ''}`} onClick={() => { setSelected(item.mandi); setEstimateInputs(current => ({ ...current, modal_price_per_quintal: item.modal_price, distance_km: item.distance_km ?? 0 })); setEstimate(null) }}><div><strong>{item.mandi}</strong><span>{item.district} · {item.distance_km != null ? `${item.distance_km} km` : 'distance unknown'}</span></div><div><strong>{money(item.modal_price)}</strong><span>{item.date}</span></div></button>)}{!quotes.length && <EmptyState title="No mandi matches" body="Try another crop or district."/>}<div className="p3-compare"><label>COMPARE WITH<select value={comparison} onChange={event => setComparison(event.target.value)}><option value="">Choose mandi</option>{quotes.filter(item => item.mandi !== first?.mandi).map(item => <option key={item.mandi}>{item.mandi}</option>)}</select></label>{first && second && <div className="admin-line"><span>{first.mandi} versus {second.mandi}</span><strong>{money(first.modal_price - second.modal_price)} difference</strong></div>}</div></Panel></div>
      <Panel className="p3-estimator"><SectionHead title="Estimated net return" aside={<Calculator size={19}/>}/><p>Enter your own quantity and local costs. The server calculates totals; values are estimates.</p><div className="p3-number-grid">{([['quantity_quintals', 'Quantity (quintals)'], ['modal_price_per_quintal', 'Modal price (₹/quintal)'], ['distance_km', 'Distance (km)'], ['transport_cost_per_km', 'Transport (₹/km)'], ['handling_cost_per_quintal', 'Handling (₹/quintal)'], ['storage_cost', 'Storage (₹)'], ['spoilage_percent', 'Estimated spoilage (%)']] as [keyof MarketEstimateInput, string][]).map(([key, label]) => <label key={key}>{label}<input className="text-input" type="number" min="0" max={key === 'spoilage_percent' ? 100 : undefined} step="any" value={estimateInputs[key]} onChange={event => updateNumber(key, event.target.value)}/></label>)}</div><button className="button primary" onClick={calculate}>Calculate estimate <ArrowUpRight size={16}/></button>{estimateError && <p className="form-error">{estimateError}</p>}{estimate && <div className="p3-estimate-result"><div><span>Gross revenue</span><strong>{money(estimate.gross_revenue)}</strong></div><div><span>Transport + handling + storage + spoilage</span><strong>{money(estimate.total_cost)}</strong></div><div><span>Estimated net return</span><strong>{money(estimate.estimated_net_return)}</strong></div><small>{estimate.note}</small></div>}</Panel><p className="p2-attribution">{data?.provenance} · Last observation {data?.last_updated ?? 'unavailable'} · Fetched {data?.fetched_at ? new Date(data.fetched_at).toLocaleString('en-IN') : 'from local fallback'}. Prices are per quintal.</p></>}
  </div>
}
