import { useQuery } from '@tanstack/react-query'
import { CircleMarker, MapContainer, TileLayer, Tooltip } from 'react-leaflet'
import { Activity, CloudSun, Database, Leaf, MapPin, ShieldCheck, Sprout } from 'lucide-react'
import { api } from '../../lib/api'
import { useTranslation } from '../../lib/i18n'
import { EmptyState, PageHeader, Panel, SectionHead, Skeleton, Stat } from '../../components/UI'

const icons = { mistral: Activity, weather: CloudSun, market: Leaf, database: Database, notifications: ShieldCheck }
export default function ProviderHealth() {
  const { t } = useTranslation()
  const query = useQuery({ queryKey: ['provider-health'], queryFn: api.providerHealth, refetchInterval: 60_000, retry: false })
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: api.adminOverview, refetchInterval: 60_000, retry: false })
  return <div className="page"><PageHeader eyebrow="PLATFORM / OPERATIONS" title={t('healthTitle')} description={t('adminDescription')}/>
    {overview.isPending ? <Skeleton className="result-loading"/> : overview.isError ? <EmptyState title={t('adminOverviewUnavailable')} body={overview.error.message}/> : <><div className="demo-notice"><ShieldCheck size={16}/><span>{overview.data.source}. Farmers, farms, clusters, and sample reports below are generated demonstration records.</span></div><div className="admin-stats"><Stat label="SYNTHETIC FARMERS" value={String(overview.data.counts.farmers)} icon={<Sprout size={19}/>}/><Stat label="SYNTHETIC FARMS" value={String(overview.data.counts.farms)} icon={<MapPin size={19}/>}/><Stat label="REPORT RECORDS" value={String(overview.data.counts.reports)} icon={<Activity size={19}/>}/><Stat label="SYNTHETIC CLUSTERS" value={String(overview.data.counts.clusters)} icon={<ShieldCheck size={19}/>}/></div><div className="p4-admin-grid"><Panel><SectionHead title={t('geographicClusterNetwork')} aside={<span className="source-badge source-demo">SYNTHETIC DEMO</span>}/><MapContainer center={[18.1, 78.8]} zoom={7} scrollWheelZoom={false} className="p4-admin-map"><TileLayer attribution='&copy; OpenStreetMap &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"/>{overview.data.clusters.map(item => <CircleMarker center={[item.latitude, item.longitude]} radius={Math.min(15, 5 + item.report_count / 4)} key={item.id} pathOptions={{ color: '#98e3b3', fillColor: '#6bcd91', fillOpacity: .8, weight: 2 }}><Tooltip>{item.crop} · {item.possible_problem} · {item.report_count} synthetic reports</Tooltip></CircleMarker>)}</MapContainer></Panel><Panel><SectionHead title={t('clusterSignals')}/><div className="p4-admin-list">{overview.data.clusters.map(item => <div className="p4-admin-list-row" key={item.id}><span><strong>{item.crop} · {item.possible_problem}</strong><small>{item.district} · synthetic observations</small></span><span>{item.report_count} reports</span></div>)}</div></Panel></div><Panel><SectionHead title={t('syntheticCropDistribution')}/><div className="p4-admin-list">{overview.data.crops.map(item => <div className="p4-admin-list-row" key={item.crop}><strong>{item.crop}</strong><span>{item.count} reports</span></div>)}</div></Panel></>}
    <div className="p4-admin-provider"><SectionHead title={t('providerHealthSection')}/>{query.isPending ? <Skeleton className="result-loading"/> : query.isError ? <EmptyState title={t('providerHealthUnavailable')} body={query.error.message}/> : <div className="p3-health-grid">{query.data.providers.map(provider => { const Icon = icons[provider.name as keyof typeof icons] ?? Activity; return <Panel className="p3-health-card" key={provider.name}><div><Icon size={22}/><span className={`p3-health-state state-${provider.state.toLowerCase()}`}>{provider.state}</span></div><h2>{provider.name[0].toUpperCase() + provider.name.slice(1)}</h2><p>{provider.detail}</p><small>Last observed: {provider.observed_at ? new Date(provider.observed_at).toLocaleString('en-IN') : 'No recent request'}</small></Panel> })}</div>}</div>
  </div>
}
