import { ArrowLeft, Check, ChevronRight, Clock3, CloudSun, Leaf, MapPin, ShieldCheck, Sparkles, Sprout } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { reports } from '../data/mockData'
import { Button, Card, PageHeading, Pill, SectionTitle } from '../components/ui'

const diagnosis = { symptoms: ['Dark brown spots with concentric rings', 'Yellowing around affected areas', 'Older leaves affected first'], actions: ['Remove and dispose of heavily affected lower leaves.', 'Water near the soil in the morning; avoid wetting foliage.', 'Allow airflow between plants and monitor new growth.'], prevent: ['Rotate out of tomatoes and potatoes next season.', 'Check nearby plants twice a week, especially after humid days.'] }
export default function CropResult() {
  const { id } = useParams()
  const report = reports.find((item) => item.id === id) || reports[0]
  return <><Link to="/reports" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-muted hover:text-ink"><ArrowLeft size={15} />Back to my reports</Link><PageHeading eyebrow={`REPORT ${report.id}`} title="Your crop health summary" description="A preliminary assessment based on the details and photo you shared." action={<Pill tone="green"><Check size={12} className="mr-1" />Reviewed</Pill>} />
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-5"><Card className="overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#eef1eb] px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="text-2xl">{report.icon}</span><div><p className="text-sm font-bold text-ink">{report.crop} · Flowering stage</p><p className="mt-1 flex items-center gap-1 text-[10px] text-muted"><Clock3 size={12} />Submitted {report.date}</p></div></div><Pill tone="amber">Preliminary result</Pill></div><div className="p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold text-muted">Possible issue</p><h2 className="display mt-1 text-2xl font-extrabold text-ink">{report.diagnosis}</h2><p className="mt-2 text-xs text-muted">A common fungal disease affecting leaves and stems</p></div><div className="rounded-xl bg-leaf-50 px-4 py-3 text-center"><p className="text-[10px] font-bold uppercase tracking-wider text-leaf-700">Confidence</p><p className="mt-0.5 text-2xl font-extrabold text-ink">{report.confidence}<span className="text-sm">%</span></p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#edf1e9]"><div className="h-full w-[89%] rounded-full bg-leaf-500" /></div><div className="mt-5 rounded-xl border border-amber-100 bg-amber-50/70 p-4"><div className="flex items-start gap-2.5"><Sparkles size={17} className="mt-0.5 shrink-0 text-amber-600" /><div><p className="text-xs font-bold text-ink">Why this might fit</p><p className="mt-1 text-xs leading-5 text-muted">Your description mentions brown spots on lower leaves. The pattern can be consistent with early blight, though other causes may look similar.</p></div></div></div></div></Card>
      <Card><SectionTitle>What we noticed</SectionTitle><div className="space-y-3">{diagnosis.symptoms.map((item) => <div key={item} className="flex items-start gap-2.5 text-xs leading-5 text-[#526158]"><span className="mt-1 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-leaf-50 text-leaf-700"><Check size={11} /></span>{item}</div>)}</div></Card>
      <Card><SectionTitle>Suggested next steps</SectionTitle><div className="space-y-3">{diagnosis.actions.map((item, index) => <div className="flex gap-3" key={item}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-leaf-50 text-xs font-extrabold text-leaf-700">{index + 1}</span><p className="pt-1 text-xs leading-5 text-[#526158]">{item}</p></div>)}</div><div className="mt-5 border-t border-[#eff2ec] pt-4"><p className="mb-3 text-xs font-bold text-ink">For prevention</p>{diagnosis.prevent.map((item) => <p className="mb-2 flex gap-2 text-xs leading-5 text-muted" key={item}><span className="text-leaf-700">•</span>{item}</p>)}</div></Card></div>
      <div className="space-y-5"><Card className="bg-[#f1f6ec]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="rounded-lg bg-white p-2 text-leaf-700"><CloudSun size={17} /></span><div><p className="text-xs font-bold text-ink">Local conditions</p><p className="mt-0.5 text-[10px] text-muted">Warangal · Today</p></div></div><Pill tone="blue">Helpful context</Pill></div><div className="mt-4 rounded-xl bg-white p-4"><p className="text-xs leading-5 text-[#526158]">Warm, humid conditions this week can favor fungal spread. Check leaves after rainfall and water at the base of plants.</p><div className="mt-3 flex items-center justify-between border-t border-[#eff2ec] pt-3 text-[10px] font-semibold text-muted"><span>Humidity 68%</span><span>Rain forecast Thu</span></div></div></Card>
        <Card><SectionTitle>Report details</SectionTitle><div className="space-y-3 text-xs"><div className="flex justify-between"><span className="text-muted">Report ID</span><span className="font-bold text-ink">{report.id}</span></div><div className="flex justify-between"><span className="text-muted">Severity</span><Pill tone="amber">{report.severity}</Pill></div><div className="flex justify-between"><span className="text-muted">Location</span><span className="font-semibold text-ink">Warangal</span></div><div className="flex justify-between"><span className="text-muted">Review status</span><span className="font-semibold text-leaf-700">{report.status}</span></div></div></Card>
        <Card><div className="flex items-start gap-3"><span className="rounded-xl bg-sky-50 p-2.5 text-sky-700"><ShieldCheck size={18} /></span><div><p className="text-xs font-bold text-ink">Keep an expert in the loop</p><p className="mt-1 text-[11px] leading-5 text-muted">This is a possible diagnosis, not a confirmed one. An agricultural officer can help verify the cause.</p><button className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-leaf-700">Learn how to get help <ChevronRight size={13} /></button></div></div></Card>
        <Link to="/crops"><Button variant="secondary" className="w-full"><Sprout size={15} />View my crops</Button></Link>
      </div></div>
  </>
}
