import { ArrowRight, ArrowUpRight, CloudRain, Droplets, Leaf, MapPin, Plus, Sun, Wind } from 'lucide-react'
import { Link } from 'react-router-dom'
import { alerts, crops, farmer, marketPrices, reports } from '../data/mockData'
import { Avatar, Button, Card, PageHeading, Pill, ProgressBar, SeeAll, SectionTitle, StatCard } from '../components/ui'

function WeatherCard() {
  return <Card className="relative overflow-hidden border-0 bg-ink p-6 text-white sm:p-7"><div className="absolute -right-10 -top-16 h-52 w-52 rounded-full bg-white/[.035]" /><div className="absolute -bottom-24 right-24 h-48 w-48 rounded-full bg-lime/[.05]" /><div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-1.5 text-xs font-semibold text-white/60"><MapPin size={13} />{farmer.location}</div><p className="mt-6 text-xs font-medium text-white/65">Good morning, {farmer.name.split(' ')[0]} <span>☀️</span></p><p className="display mt-1 text-5xl font-bold tracking-tight">31<span className="ml-1 text-3xl font-medium text-white/70">°C</span></p><p className="mt-1 text-sm font-semibold">Partly cloudy</p></div><div className="flex h-[76px] w-[76px] items-center justify-center rounded-[24px] bg-[#f1c96f]/15 text-[#f1c96f]"><Sun size={40} strokeWidth={1.5} /></div></div><div className="relative mt-7 grid grid-cols-3 divide-x divide-white/10 border-t border-white/10 pt-4"><div className="flex items-center gap-2"><Droplets size={16} className="text-sky-300" /><div><p className="text-sm font-bold">68%</p><p className="text-[10px] text-white/50">Humidity</p></div></div><div className="flex items-center justify-center gap-2"><Wind size={16} className="text-white/60" /><div><p className="text-sm font-bold">12 km/h</p><p className="text-[10px] text-white/50">Wind</p></div></div><div className="flex items-center justify-end gap-2"><CloudRain size={16} className="text-sky-300" /><div><p className="text-sm font-bold">8 mm</p><p className="text-[10px] text-white/50">Thu forecast</p></div></div></div></Card>
}

function CropMini({ crop }) { return <div className="rounded-xl border border-[#edf0ea] p-4"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl text-lg ${crop.color === 'tomato' ? 'bg-red-50' : crop.color === 'rice' ? 'bg-amber-50' : 'bg-orange-50'}`}>{crop.color === 'tomato' ? '🍅' : crop.color === 'rice' ? '🌾' : '🌶️'}</div><div><p className="text-sm font-bold text-ink">{crop.name}</p><p className="mt-0.5 text-[10px] text-muted">{crop.variety} · {crop.area}</p></div></div><Pill tone={crop.health === 'Good' ? 'green' : 'amber'}>{crop.health}</Pill></div><div className="mt-4 flex items-center justify-between text-[10px] text-muted"><span>{crop.stage}</span><span>{crop.progress}%</span></div><div className="mt-2"><ProgressBar value={crop.progress} /></div></div> }

export default function Home() {
  return <><PageHeading eyebrow="Thursday, September 25, 2026" title={`Good morning, ${farmer.name.split(' ')[0]} 👋`} description="Here's what's happening on your farm today." action={<Link to="/report"><Button><Plus size={16} />New report</Button></Link>} />
    <div className="grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><WeatherCard /><Card className="soft-grid relative overflow-hidden"><SectionTitle action={<SeeAll to="/market" />}>Market snapshot</SectionTitle><div className="flex items-center justify-between rounded-xl bg-white/85 p-4 shadow-sm"><div><p className="text-xs font-semibold text-muted">Tomato · Enumamula</p><p className="mt-2 text-[28px] font-extrabold tracking-tight text-ink">₹2,610<span className="ml-1 text-xs font-semibold text-muted">/ quintal</span></p><p className="mt-1 flex items-center gap-1 text-[11px] font-bold text-leaf-700"><ArrowUpRight size={14} />7.8% this week</p></div><div className="rounded-xl bg-leaf-50 px-3 py-2 text-center"><p className="text-[10px] font-semibold text-muted">Updated</p><p className="mt-1 text-xs font-extrabold text-leaf-700">Today</p></div></div><div className="mt-4 flex items-center justify-between text-[11px] text-muted"><span>Best nearby modal price</span><Link to="/market" className="font-bold text-ink">Compare mandis <ArrowRight size={13} className="inline" /></Link></div></Card></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active crops" value="3 crops" detail="Across 8 acres" icon={Leaf} tone="green" /><StatCard label="Open reports" value="2 reports" detail="1 needs your attention" icon={MapPin} tone="amber" /><StatCard label="Nearby alerts" value="2 alerts" trend="+1" detail="in the last 24 hours" icon={CloudRain} tone="red" /><StatCard label="This week's rain" value="11 mm" detail="Light rain expected" icon={Droplets} tone="blue" /></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><Card><SectionTitle action={<SeeAll to="/crops" />}>Your active crops</SectionTitle><div className="space-y-3">{crops.map((crop) => <CropMini key={crop.id} crop={crop} />)}</div></Card><Card><SectionTitle action={<SeeAll to="/alerts" />}>Community watch <span className="ml-1 rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-700">{alerts.length} nearby</span></SectionTitle><div className="space-y-1">{alerts.slice(0, 2).map((alert) => <div key={alert.disease} className="flex items-start gap-3 border-b border-[#eff2ec] py-3 last:border-0"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#f4f6f0] text-lg">{alert.icon}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-xs font-bold text-ink">{alert.disease}</p><Pill tone={alert.severity === 'High' ? 'red' : 'amber'}>{alert.severity}</Pill></div><p className="mt-1 text-[11px] text-muted">{alert.district} · {alert.distance} away · {alert.time}</p></div></div>)}</div><div className="mt-3 rounded-xl bg-[#f8faf6] p-3 text-[11px] leading-5 text-muted"><span className="font-bold text-ink">Field note:</span> Check the undersides of tomato leaves this week. Warm, humid weather may encourage fungal spots.</div></Card></div>
    <Card className="mt-5"><SectionTitle action={<SeeAll to="/reports" />}>Recent activity</SectionTitle><div className="divide-y divide-[#eff2ec]">{reports.slice(0, 3).map((report) => <Link to={`/reports/${report.id}`} key={report.id} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f5f7f2] text-lg">{report.icon}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-ink">{report.diagnosis} · {report.crop}</p><p className="mt-1 text-[10px] text-muted">{report.id} · {report.date}</p></div><Pill tone={report.severity === 'High' ? 'red' : report.severity === 'Medium' ? 'amber' : 'green'}>{report.severity}</Pill><ArrowRight size={15} className="text-[#aab4aa]" /></Link>)}</div></Card>
    <div className="mt-4 flex items-center justify-between rounded-2xl bg-[#e8f0de] px-5 py-4"><div className="flex items-center gap-3"><Avatar initials={farmer.avatar} /><div><p className="text-xs font-bold text-ink">Your farm profile is looking good</p><p className="mt-1 text-[11px] text-muted">Add a soil test for more tailored crop recommendations.</p></div></div><Link to="/farm"><Button variant="secondary">Add soil details <ArrowRight size={14} /></Button></Link></div>
  </>
}
