import { ArrowRight, CalendarDays, Droplets, Leaf, Plus, Sprout, SunMedium } from 'lucide-react'
import { Link } from 'react-router-dom'
import { crops, farmer } from '../data/mockData'
import { Button, Card, PageHeading, Pill, ProgressBar, SectionTitle, StatCard } from '../components/ui'

const emoji = { tomato: '🍅', rice: '🌾', chilli: '🌶️' }
export default function MyCrops() {
  return <><PageHeading eyebrow="Your growing season" title="My crops" description="Keep track of crop stages, field notes, and the next things to watch." action={<Button><Plus size={15} />Add crop</Button>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Active crops" value="3" detail="Across 3 crop cycles" icon={Sprout} /><StatCard label="Total cultivated area" value="8 acres" detail={farmer.farm} icon={Leaf} tone="amber" /><StatCard label="Growing season" value="Kharif" detail="Monsoon · 2026" icon={SunMedium} tone="blue" /></div>
    <div className="grid gap-5 xl:grid-cols-2">{crops.map((crop) => <Card key={crop.id} className="relative overflow-hidden"><div className={`absolute inset-x-0 top-0 h-1 ${crop.health === 'Watch' ? 'bg-amber-400' : 'bg-leaf-500'}`} /><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-3.5"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#f4f6f0] text-3xl">{emoji[crop.color]}</span><div><p className="text-lg font-extrabold text-ink">{crop.name}</p><p className="mt-0.5 text-xs text-muted">{crop.variety} · {crop.area}</p></div></div><Pill tone={crop.health === 'Watch' ? 'amber' : 'green'}>{crop.health === 'Watch' ? 'Needs a look' : 'Looking good'}</Pill></div><div className="mt-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted">Growth progress</p><p className="mt-1 text-sm font-bold text-ink">{crop.stage}</p></div><span className="text-sm font-extrabold text-leaf-700">{crop.progress}%</span></div><div className="mt-3"><ProgressBar value={crop.progress} color={crop.health === 'Watch' ? 'bg-amber-400' : 'bg-leaf-500'} /></div><div className="mt-4 flex flex-wrap gap-4 text-[10px] font-semibold text-muted"><span className="flex items-center gap-1.5"><CalendarDays size={13} />Sown Jun 18</span><span className="flex items-center gap-1.5"><Droplets size={13} />Drip irrigation</span><span className="flex items-center gap-1.5">Season: {crop.season}</span></div></div><div className="mt-5 flex items-center justify-between border-t border-[#eff2ec] pt-4"><p className="text-[11px] text-muted">{crop.health === 'Watch' ? 'Leaf tip discoloration reported recently' : 'Last field update · 2 days ago'}</p><Link to="/reports/RPT-2408" className="flex items-center gap-1 text-[11px] font-bold text-leaf-700">View details <ArrowRight size={13} /></Link></div></Card>)}</div>
    <Card className="mt-5"><SectionTitle>Season calendar <span className="ml-1 text-xs font-normal text-muted">· Kharif 2026</span></SectionTitle><div className="grid gap-0 sm:grid-cols-4">{[{ month: 'JUN', task: 'Sowing & transplanting', done: true }, { month: 'JUL–AUG', task: 'Vegetative growth', done: true }, { month: 'SEP–OCT', task: 'Flowering & fruiting', done: false }, { month: 'NOV', task: 'Harvest window', done: false }].map((item) => <div key={item.month} className="relative border-l border-[#e8ede3] py-2 pl-5 first:border-0"><span className={`absolute -left-1 top-3 h-2 w-2 rounded-full ring-4 ring-white ${item.done ? 'bg-leaf-500' : 'bg-[#d6ded2]'}`} /><p className={`text-[10px] font-extrabold tracking-wider ${item.done ? 'text-leaf-700' : 'text-muted'}`}>{item.month}</p><p className="mt-2 text-xs font-semibold text-ink">{item.task}</p><p className="mt-1 text-[10px] text-muted">{item.done ? 'Completed' : 'Upcoming'}</p></div>)}</div></Card>
  </>
}
