import { ArrowDownUp, CalendarDays, ChevronDown, Filter, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { reports } from '../data/mockData'
import { Button, Card, PageHeading, Pill, SectionTitle } from '../components/ui'

export default function MyReports() { return <><PageHeading eyebrow="Your crop health history" title="My reports" description="Review past reports, follow up on open issues, and see what's changed." action={<Link to="/report"><Button><Plus size={15} />New report</Button></Link>} />
  <div className="mb-5 grid gap-4 sm:grid-cols-3">{[{ label: 'Total reports', value: '12', color: 'text-ink' }, { label: 'Needs follow-up', value: '2', color: 'text-amber-700' }, { label: 'Resolved', value: '8', color: 'text-leaf-700' }].map((stat) => <Card className="p-4" key={stat.label}><p className="text-[11px] font-semibold text-muted">{stat.label}</p><p className={`mt-2 text-2xl font-extrabold ${stat.color}`}>{stat.value}</p></Card>)}</div>
  <Card className="p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#edf0ea] p-5"><div><SectionTitle className="mb-0">All reports <Pill tone="gray">12 total</Pill></SectionTitle></div><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 rounded-xl border border-[#e7ebe4] bg-white px-3 py-2 text-xs text-muted"><Search size={14} /><input placeholder="Search reports" className="w-28 bg-transparent outline-none placeholder:text-[#a3ada4] sm:w-36" /></label><button className="flex items-center gap-1.5 rounded-xl border border-[#e7ebe4] px-3 py-2 text-xs font-semibold text-muted"><Filter size={13} />All status <ChevronDown size={12} /></button><button className="rounded-xl border border-[#e7ebe4] p-2 text-muted" aria-label="Sort reports"><ArrowDownUp size={15} /></button></div></div>
    <div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[650px] text-left"><thead className="bg-[#fafbf9] text-[10px] font-bold uppercase tracking-wider text-[#9aa69c]"><tr><th className="px-5 py-3">Report</th><th className="px-4 py-3">Possible issue</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">Status</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-[#eff2ec]">{reports.map((report) => <tr key={report.id} className="transition hover:bg-[#fcfdfb]"><td className="px-5 py-4"><Link to={`/reports/${report.id}`} className="flex items-center gap-2.5"><span className="text-lg">{report.icon}</span><span><span className="block text-xs font-bold text-ink">{report.crop}</span><span className="mt-0.5 block text-[10px] text-muted">{report.id}</span></span></Link></td><td className="px-4 py-4"><Link to={`/reports/${report.id}`} className="text-xs font-semibold text-ink hover:text-leaf-700">{report.diagnosis}</Link><p className="mt-0.5 text-[10px] text-muted">{report.issue}</p></td><td className="px-4 py-4 text-xs font-bold text-ink">{report.confidence}%</td><td className="px-4 py-4"><Pill tone={report.severity === 'High' ? 'red' : report.severity === 'Medium' ? 'amber' : 'green'}>{report.severity}</Pill></td><td className="px-4 py-4"><Pill tone={report.status === 'Resolved' || report.status === 'Reviewed' ? 'green' : 'amber'}>{report.status}</Pill></td><td className="px-5 py-4 text-[10px] text-muted">{report.date}</td></tr>)}</tbody></table></div>
    <div className="divide-y divide-[#eff2ec] sm:hidden">{reports.map((report) => <Link key={report.id} to={`/reports/${report.id}`} className="flex items-start gap-3 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f5f7f2] text-xl">{report.icon}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-xs font-bold text-ink">{report.diagnosis}</p><Pill tone={report.severity === 'High' ? 'red' : report.severity === 'Medium' ? 'amber' : 'green'}>{report.severity}</Pill></div><p className="mt-1 text-[10px] text-muted">{report.crop} · {report.id} · {report.date}</p><div className="mt-2"><Pill tone={report.status === 'Resolved' || report.status === 'Reviewed' ? 'green' : 'amber'}>{report.status}</Pill></div></div></Link>)}</div>
    <div className="flex items-center justify-between border-t border-[#edf0ea] px-5 py-4 text-[10px] text-muted"><span>Showing 4 of 12 reports</span><div className="flex gap-2"><button className="rounded-lg border border-[#e8ece5] px-3 py-1.5">Previous</button><button className="rounded-lg border border-[#e8ece5] px-3 py-1.5">Next</button></div></div></Card>
  </> }
