import { Activity, Bell, ChevronRight, Clock3, MapPin, Navigation, Radio, ShieldAlert, Sprout } from 'lucide-react'
import { alerts } from '../data/mockData'
import { Button, Card, PageHeading, Pill, SectionTitle, StatCard } from '../components/ui'

function MapPreview() { return <div className="relative min-h-[285px] overflow-hidden rounded-2xl border border-[#e3eadf] bg-[#eaf0e4] soft-grid"><div className="absolute inset-0 opacity-60" style={{ backgroundImage: 'linear-gradient(32deg, transparent 48%, #fff 48.5%, #fff 50%, transparent 50.5%),linear-gradient(112deg, transparent 43%, #fff 43.5%, #fff 44.5%, transparent 45%)', backgroundSize: '145px 115px, 190px 160px' }} /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 560 300" preserveAspectRatio="none"><path d="M-20,225 C90,210 110,115 230,145 S390,230 590,80" fill="none" stroke="#b8cba8" strokeWidth="32" opacity=".55"/><path d="M-20,225 C90,210 110,115 230,145 S390,230 590,80" fill="none" stroke="#fff" strokeWidth="3" strokeDasharray="8 8"/><path d="M90,-20 C150,65 320,80 420,165 S480,260 560,290" fill="none" stroke="#fff" strokeWidth="7" opacity=".8"/></svg><div className="absolute left-[48%] top-[43%] flex h-14 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-white/80 ring-8 ring-leaf-500/10"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-leaf-600 text-white shadow"><Sprout size={17} /></div></div><div className="absolute left-[24%] top-[28%] flex h-9 w-9 items-center justify-center rounded-full border-2 border-white bg-red-500 text-sm shadow-md">🍅<span className="absolute -right-1 -top-1 h-3 w-3 animate-pulse rounded-full bg-red-300" /></div><div className="absolute left-[70%] top-[68%] flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-amber-400 text-xs shadow-md">🌾</div><div className="absolute left-[80%] top-[23%] flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-amber-400 text-xs shadow-md">🌶️</div><div className="absolute bottom-3 left-3 rounded-lg bg-white/90 px-3 py-2 text-[10px] font-semibold text-muted shadow-sm backdrop-blur">OpenStreetMap style preview · Not to scale</div><div className="absolute right-3 top-3 flex items-center gap-1 rounded-lg bg-white/90 px-2.5 py-2 text-[10px] font-bold text-ink shadow-sm"><Navigation size={12} className="text-leaf-700" />10 km radius</div></div> }

export default function NearbyAlerts() { return <><PageHeading eyebrow="Community crop watch" title="Nearby alerts" description="See recent crop health reports shared in your area. Locations are approximate to protect farmer privacy." action={<Button variant="secondary"><MapPin size={15} />Warangal · 10 km</Button>} />
  <div className="mb-5 grid gap-4 sm:grid-cols-3"><StatCard label="Active advisories" value="2" detail="In your selected radius" icon={ShieldAlert} tone="amber" /><StatCard label="Farmers reached" value="14" detail="Community updates this week" icon={Radio} tone="blue" /><StatCard label="Following" value="3 crops" detail="Tomato, rice, chilli" icon={Sprout} /></div>
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card><SectionTitle action={<button className="text-xs font-bold text-leaf-700">Change radius</button>}>Activity around you <Pill tone="green">Live preview</Pill></SectionTitle><MapPreview /><div className="mt-4 flex flex-wrap gap-4 text-[10px] font-semibold text-muted"><span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-leaf-600" />Your approximate area</span><span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-red-500" />High attention</span><span className="flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-amber-400" />Advisory</span></div></Card>
    <Card><SectionTitle>Recent community reports</SectionTitle><div className="space-y-3">{alerts.map((alert) => <div key={alert.disease} className="rounded-xl border border-[#edf0ea] p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#f5f7f2] text-xl">{alert.icon}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold text-ink">{alert.disease}</p><p className="mt-1 text-[10px] text-muted">{alert.crop} · {alert.district}</p></div><Pill tone={alert.severity === 'High' ? 'red' : 'amber'}>{alert.severity}</Pill></div><div className="mt-3 flex items-center justify-between border-t border-[#eff2ec] pt-2.5 text-[10px] text-muted"><span className="flex items-center gap-1"><MapPin size={11} />Approx. {alert.distance}</span><span className="flex items-center gap-1"><Clock3 size={11} />{alert.time}</span></div><p className="mt-2 text-[10px] font-semibold text-muted">{alert.reports} similar reports nearby</p></div></div></div>)}</div></Card></div>
  <Card className="mt-5 flex flex-wrap items-center justify-between gap-4 bg-[#f7f9f4]"><div className="flex items-start gap-3"><span className="rounded-xl bg-white p-2.5 text-leaf-700"><Bell size={17} /></span><div><p className="text-xs font-bold text-ink">Choose which updates matter to you</p><p className="mt-1 text-[11px] text-muted">Follow crops you grow to see the most relevant community advisories.</p></div></div><Button variant="secondary">Manage crop alerts <ChevronRight size={14} /></Button></Card>
  </> }
