import { useState } from 'react'
import { Camera, Check, ChevronDown, ImagePlus, Mic, Send, Sparkles, Upload, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { crops } from '../data/mockData'
import { useAppStore } from '../store/useAppStore'
import { Button, Card, PageHeading, Pill } from '../components/ui'

export default function ReportProblem() {
  const selected = useAppStore((state) => state.selectedCrop)
  const setSelected = useAppStore((state) => state.setSelectedCrop)
  const [description, setDescription] = useState('')
  const [file, setFile] = useState(null)
  const [submitted, setSubmitted] = useState(false)
  const navigate = useNavigate()
  const handleSubmit = (event) => { event.preventDefault(); setSubmitted(true); window.setTimeout(() => navigate('/reports/RPT-2408'), 450) }
  return <><PageHeading eyebrow="Crop health" title="Tell us what's happening" description="Share a photo or describe what you're seeing. A little detail helps make the guidance more useful." action={<Pill tone="blue"><Sparkles size={12} className="mr-1" />Mock preview</Pill>} />
    <form onSubmit={handleSubmit} className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><Card><label className="mb-3 block text-sm font-bold text-ink">Which crop needs attention?</label><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{crops.map((crop) => <button type="button" onClick={() => setSelected(crop.name)} key={crop.id} className={`flex items-center gap-2.5 rounded-xl border p-3 text-left transition ${selected === crop.name ? 'border-leaf-500 bg-leaf-50 ring-2 ring-leaf-500/10' : 'border-[#e9eee5] hover:border-leaf-200'}`}><span className="text-xl">{crop.color === 'tomato' ? '🍅' : crop.color === 'rice' ? '🌾' : '🌶️'}</span><span><span className="block text-xs font-bold text-ink">{crop.name}</span><span className="mt-0.5 block text-[10px] text-muted">{crop.variety}</span></span>{selected === crop.name && <Check size={14} className="ml-auto text-leaf-700" />}</button>)}</div><button type="button" className="mt-3 flex items-center gap-2 text-xs font-bold text-leaf-700"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-leaf-50"><span className="text-base">＋</span></span>Add another crop</button></Card>
      <Card><div className="flex items-center justify-between"><div><label htmlFor="description" className="text-sm font-bold text-ink">Describe the symptoms</label><p className="mt-1 text-xs text-muted">When did it start? Which part of the plant is affected?</p></div><button type="button" className="flex items-center gap-1.5 rounded-lg border border-[#e8ece4] px-2.5 py-2 text-[11px] font-bold text-muted hover:text-ink"><Mic size={14} />Voice note</button></div><textarea id="description" value={description} onChange={(event) => setDescription(event.target.value)} rows={5} placeholder="For example: Brown spots appeared on the lower leaves about four days ago. They seem to be spreading after the rain..." className="mt-4 w-full resize-none rounded-xl border border-[#e6ebe2] bg-[#fbfcfa] p-4 text-sm leading-6 text-ink outline-none placeholder:text-[#aab4ac] focus:border-leaf-500 focus:ring-4 focus:ring-leaf-500/10" /><div className="mt-2 flex justify-between text-[10px] text-muted"><span>Write in English or Telugu</span><span>{description.length}/1000</span></div></Card>
      <Card><div className="mb-4 flex items-start justify-between"><div><p className="text-sm font-bold text-ink">Add a photo <span className="font-normal text-muted">(optional)</span></p><p className="mt-1 text-xs text-muted">Clear close-up photos help identify visible symptoms.</p></div><Pill tone="gray">JPG, PNG · up to 5 MB</Pill></div>{file ? <div className="flex items-center gap-3 rounded-xl border border-leaf-100 bg-leaf-50 p-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white text-leaf-700"><Camera size={18} /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-ink">{file.name}</p><p className="mt-1 text-[10px] text-muted">{(file.size / 1024 / 1024).toFixed(2)} MB · Ready to include</p></div><button type="button" aria-label="Remove photo" onClick={() => setFile(null)} className="rounded-lg p-2 text-muted hover:bg-white"><X size={16} /></button></div> : <label className="flex min-h-[150px] cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#d8e0d4] bg-[#fafbf8] text-center transition hover:border-leaf-500 hover:bg-leaf-50/50"><span className="mb-2 flex h-10 w-10 items-center justify-center rounded-xl bg-white text-leaf-700 shadow-sm"><ImagePlus size={19} /></span><span className="text-xs font-bold text-ink">Click to browse or drag a photo here</span><span className="mt-1.5 text-[10px] text-muted">Try to capture both the affected area and the whole plant</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const next = event.target.files?.[0]; if (next && next.size <= 5 * 1024 * 1024) setFile(next) }} /></label>}</Card></div>
      <div className="space-y-5"><Card><p className="text-sm font-bold text-ink">A few more details</p><label className="mt-5 block text-xs font-bold text-ink">Crop stage</label><div className="relative mt-2"><select className="w-full appearance-none rounded-xl border border-[#e6ebe2] bg-white px-3.5 py-3 text-xs text-ink outline-none focus:border-leaf-500"><option>Flowering</option><option>Seedling</option><option>Vegetative</option><option>Fruiting</option><option>Harvest</option></select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-muted" /></div><label className="mt-5 block text-xs font-bold text-ink">When did you first notice this?</label><div className="relative mt-2"><select className="w-full appearance-none rounded-xl border border-[#e6ebe2] bg-white px-3.5 py-3 text-xs text-ink outline-none focus:border-leaf-500"><option>Within the last few days</option><option>Today</option><option>About a week ago</option><option>More than a week ago</option></select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-muted" /></div><label className="mt-5 block text-xs font-bold text-ink">Your location</label><div className="mt-2 flex items-center justify-between rounded-xl border border-[#e6ebe2] px-3.5 py-3"><div className="flex items-center gap-2"><span className="text-sm">📍</span><span className="text-xs font-semibold text-ink">Warangal, Telangana</span></div><button type="button" className="text-[10px] font-bold text-leaf-700">Edit</button></div></Card>
      <Card className="bg-[#f7f9f4]"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-leaf-700"><Sparkles size={17} /></div><div><p className="text-xs font-bold text-ink">What happens next?</p><p className="mt-1 text-[11px] leading-5 text-muted">Your report will be reviewed using the symptoms and photo you share. You’ll see possible causes and practical next steps here.</p><p className="mt-3 text-[10px] font-semibold text-muted">Any advice is a starting point. Ask a local expert before applying treatment.</p></div></div></Card>
      <Button className="w-full py-3.5" type="submit" disabled={submitted}>{submitted ? <><Check size={16} />Saving your report...</> : <><Send size={15} />Submit report</>}</Button><p className="text-center text-[10px] text-muted">Mock mode · Nothing will be sent to a server</p></div></form>
  </>
}
