import { useEffect, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { ArrowUpRight, CheckCircle2, FileImage, Plus, RefreshCw, Search } from 'lucide-react'
import { api } from '../../lib/api'
import { listQueuedReports, QUEUE_EVENT, syncQueuedReports } from '../../lib/offlineQueue'
import { useTranslation } from '../../lib/i18n'
import { EmptyState, PageHeader, Panel, SeverityBadge, Skeleton, Stat } from '../../components/UI'

export default function MyReports() {
  const { t } = useTranslation()
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('All statuses')
  const [syncing, setSyncing] = useState(false)
  const [syncError, setSyncError] = useState('')
  const reportsQuery = useQuery({ queryKey: ['reports'], queryFn: api.reports, refetchInterval: 30_000 })
  const queueQuery = useQuery({ queryKey: ['offline-reports'], queryFn: listQueuedReports, staleTime: 0, networkMode: 'always' })
  useEffect(() => { const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['offline-reports'] }) }; window.addEventListener(QUEUE_EVENT, refresh); return () => window.removeEventListener(QUEUE_EVENT, refresh) }, [queryClient])
  const queue = queueQuery.data ?? []
  const reports = (reportsQuery.data ?? []).filter(item => !queue.some(queued => queued.serverId === item.id))
  const filtered = reports.filter(item => `${item.crop} ${item.field} ${item.id} ${item.crop_health?.finding.possible_problem ?? ''}`.toLowerCase().includes(search.toLowerCase()) && (status === 'All statuses' || item.status === status))
  async function sync() { setSyncing(true); setSyncError(''); try { await syncQueuedReports(); await Promise.all([queryClient.invalidateQueries({ queryKey: ['offline-reports'] }), queryClient.invalidateQueries({ queryKey: ['reports'] }), queryClient.invalidateQueries({ queryKey: ['notifications'] })]) } catch (error) { setSyncError(error instanceof Error ? error.message : 'Offline storage unavailable.') } finally { setSyncing(false) } }
  return <div className="page"><PageHeader eyebrow="YOUR FARM / FIELD HISTORY" title={t('reports')} description="Submitted observations and reports waiting in this browser." action={<Link to="/report" className="button primary"><Plus size={17}/> New report</Link>}/>
    <div className="report-stats"><Stat label="TOTAL REPORTS" value={String(reports.length + queue.length).padStart(2, '0')} icon={<FileImage size={19}/>}/><Stat label="ANALYSED" value={String(reports.filter(item => item.status === 'completed').length).padStart(2, '0')} icon={<CheckCircle2 size={19}/>}/><Stat label="WAITING TO SYNC" value={String(queue.length).padStart(2, '0')} icon={<RefreshCw size={19}/>}/></div>
    {queue.length > 0 && <Panel className="p3-queue-panel"><div className="section-head"><h2>{t('waitingSync')}</h2><button className="button secondary" disabled={syncing || !navigator.onLine} onClick={sync}><RefreshCw size={16}/>{syncing ? 'Syncing...' : t('syncNow')}</button></div><p>Saved on this device in IndexedDB. Keep this browser's site data until synchronization completes.</p>{syncError && <p className="form-error" role="alert">{syncError}</p>}{queue.map(item => <div className="p3-queue-row" key={item.id}><div><strong>{item.crop} · {item.field}</strong><small>{new Date(item.createdAt).toLocaleString('en-IN')} · {item.district}</small></div><span className="status-pill pending">{item.status === 'failed' ? 'Sync failed · retry available' : item.status === 'syncing' ? 'Syncing' : t('waitingSync')}</span>{item.lastError && <small>{item.lastError}</small>}</div>)}</Panel>}
    <Panel className="reports-panel"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input aria-label="Search reports" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reports..."/></div><select aria-label="Filter report status" value={status} onChange={event => setStatus(event.target.value)}>{['All statuses', 'submitted', 'processing', 'completed', 'failed'].map(item => <option key={item}>{item}</option>)}</select></div>{reportsQuery.isPending ? <Skeleton className="result-loading"/> : reportsQuery.isError ? <EmptyState title="Server reports unavailable" body={reportsQuery.error.message} action={<button className="button secondary" onClick={() => reportsQuery.refetch()}>Retry</button>}/> : filtered.length ? <div className="report-table-wrap"><table className="data-table"><thead><tr><th>REPORT</th><th>CROP / FIELD</th><th>DATE</th><th>SEVERITY</th><th>STATUS / SOURCE</th><th/></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><strong>{item.crop_health?.finding.possible_problem ?? 'Awaiting analysis'}</strong><small>{item.id.slice(0, 8)}</small></td><td>{item.crop}<small>{item.field}</small></td><td>{new Date(item.created_at).toLocaleDateString('en-IN')}</td><td>{item.crop_health ? <SeverityBadge severity={(item.crop_health.finding.severity[0].toUpperCase() + item.crop_health.finding.severity.slice(1)) as 'Low' | 'Moderate' | 'High'}/> : '—'}</td><td><span className={`status-pill ${item.status !== 'completed' ? 'pending' : ''}`}>{item.status}</span><small>{item.is_synthetic ? 'SYNTHETIC · ' : ''}{item.crop_health?.source ?? 'Not analysed'}</small></td><td><Link to={`/result/${item.id}`} aria-label={`View ${item.crop} report`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div> : <EmptyState title="No server reports found" body={queue.length ? 'Your queued observations appear above.' : reports.length ? 'Try another search or status filter.' : 'Submit a crop observation to begin your field history.'} action={!queue.length && !reports.length && <Link className="button primary" to="/report">Create report</Link>}/>}</Panel></div>
}
